routes/web.php
<?php

  Route::get('/', 'ProductController@index');
  Route::resource('/products', 'ProductController');

  Route::post('/avatar', 'ProductController@avatar');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [ 'name', 'picture' , 'description', 'price'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

  namespace App\Http\Controllers;

  use App\Http\Requests\ProductStoreRequest;
  use App\Product;
  use App\Services\ProductService as ProductService;
  use Illuminate\Http\Request;

  class ProductController extends Controller
  {
    protected $productService;

    public function __construct(Product $productModel)
    {
      $this->productService = new ProductService($productModel);
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      $sortable = array('name', 'price');
      $products = $this->productService->getAll($request, $sortable);
      return view('product.index', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProductStoreRequest $request
     * @return void
     */
    public function store(ProductStoreRequest $request)
    {
      $this->productService->create($request);
      return redirect()->route('products.index')->with(['status' => 'Product created successfully']);

    }

    /**
     * Display the specified resource.
     *
     * @param $id
     * @return Product
     */
    public function show($id)
    {
      return view('product.show', ['product' => $this->productService->show($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      return view('product.edit', ['product' => $this->productService->show($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProductStoreRequest $request
     * @param Request
     * @return void
     */
    public function update(ProductStoreRequest $request, $id)
    {
      $this->productService->update($request, $id);
      return redirect()->route('products.index')->with(['status' => 'Product updated successfully']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return void
     */
    public function destroy($id)
    {
      $this->productService->delete($id);
      return redirect()->route('products.index')->with(['status' => 'Product deleted successfully']);;
    }

  }

resources/views/product/create.blade.php
@extends('skeleton.master')

@section('content')

    <div class="container">

        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        <div class="panel panel-default">
            <div class="panel-heading"><h1>Create a new product</h1></div>
            <div class="panel-body">
                <form action="{{route('products.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label> Name</label>
                                <input class="form-control" type="text" name="name" placeholder="Enter Product Name"
                                       required value="{{old('name')}}">
                            </div>

                            {{--Descrition--}}

                            <div class="form-group">
                                <label></b>Description</label><br>

                                <textarea class="form-control" name="description"
                                          required>{{ old('description') }}</textarea>
                            </div>

                            {{--price --}}
                            <div class="form-group">
                                <label> Price</label>
                                <input class="form-control" name="price" placeholder="Enter Product Name" type="number"
                                       step="0.01" required value="{{old('price')}}">
                            </div>

                            {{--image--}}
                            <div class="form-group">
                                <label> Upload Image * </label>
                                <input class="form-control" name="picture" placeholder="Enter Product Name" type="file"
                                       required value="{{old('picture')}}">
                            </div>


                            <div class="form-group">
                                <ul>
                                    @foreach($errors->all()  as $message)
                                        <li class="alert alert-danger">{{$message}}</li>
                                    @endforeach
                                </ul>

                            </div>
                            <button type="submit" class="btn btn-success" STYLE="width: 100%">Create</button>

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>





@endsection

resources/views/product/edit.blade.php
@extends('skeleton.master')

@section('content')
    <div class="container" style="margin-top: 100px">

        <span class="text-center">
            <a href="{{ route('products.index') }}" class="btn btn-primary">Go Back</a>
        </span>
        <div class="panel panel-default">
            <div class="panel-heading"><h3>Editing - {{$product->name}} </h3></div>
            <div class="panel-body">

                <form action="{{ route('products.update', $product->id) }}" method="POST" enctype="multipart/form-data">
                    @method('PATCH')
                    @csrf
                    <div class="row">
                        <div class="col">
                            <div class="form-group">

                                <input type="hidden" name="id" value="{{$product->id}}">
                                <label> Name</label>
                                <input class="form-control" type="text" name="name" placeholder="Enter Product Name"
                                       required value="{{$product->name}}">
                            </div>

                            {{--Descrition--}}

                            <div class="form-group">
                                <label></b>Description</label><br>

                                <textarea class="form-control" name="description"
                                          required>{{ $product->description }}</textarea>
                            </div>

                            {{--price --}}
                            <div class="form-group">
                                <label> Price</label>
                                <input class="form-control" name="price" placeholder="Enter Product Name" type="number"
                                       step="0.01" required value="{{$product->price}}">
                            </div>

                            {{--image--}}
                            <div class="form-group">
                                <img src="{{asset("storage/$product->picture")}}">
                                <p>Upload a different picture</p>
                                <input class="form-control" name="picture" placeholder="Enter Product Name" type="file"
                                       value="{{$product->picture}}">
                                <input type="hidden" name="image" value="{{$product->picture}}">
                            </div>

                            @if($errors->IsNotEmpty())
                                <div class="form-group">
                                    <ul>
                                        @foreach($errors->all()  as $message)
                                            <li class="alert alert-danger">{{$message}}</li>
                                        @endforeach
                                    </ul>

                                </div>
                            @endif
                            <button type="submit" class="btn btn-success" STYLE="width: 100%">Save Changes</button>

                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
@endsection

resources/views/product/index.blade.php
@extends('skeleton.master')

@section('content')

    <div class="container" style="margin-top: 100px">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

        <div class="text-center">
            <a class="btn btn-primary" href="{{route('products.create')}}"> Add New Product</a>
        </div>
        @if($products->isEmpty())
            <p>No products found</p>
        @else

            <h1>Available products</h1>
            <div class="float-right">
                <p>Order By </p>
                <a href="/products/?sort=name&direction={{ request('direction') === 'asc'? 'desc': 'asc'}}">Name</a>
                <a href="/products/?sort=price&direction={{ request('direction') === 'asc'? 'desc': 'asc'}}">Price</a>
            </div>
            <table class="table table-bordered">
                <thead class="table thead-dark">
                <tr>
                    <th>Picture</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>Actions</th> {{--edit--}}

                </tr>
                </thead>
                <tbody>
                @foreach($products as $product)

                    <tr class="form-group">
                        <div class="form-group" style="margin: 20px;">
                            <td><a href="{{ route('products.show', $product->id) }}"> <img
                                            src='{{ asset("storage/$product->picture") }}' style="width: 200px; height: auto;"> </a></td>
                            <td><a href="{{ route('products.show', $product->id) }}"> {{ $product->name }} </a></td>
                            <td> {{ $product->price }}</td>
                            <td>  {{ $product->description }} </td>
                            <td>
                                <p><a class="alert alert-primary" href="{{route('products.edit', $product->id)}}">
                                        Edit</a></p>
                                <p>
                                <form action="{{route('products.destroy',$product->id) }}" method="POST"
                                      onsubmit="return confirm('You sure you want to delete?');">
                                    @csrf
                                    <input type="hidden" name="_method" value="DELETE"/>
                                    <button type="submit" class="btn btn btn-danger">Delete</button>
                                </form>
                                </p>
                            </td>

                        </div>
                    </tr>
                @endforeach
                </tbody>

            </table>

            {{ $products->links() }}
        @endif
    </div>

@endsection

resources/views/product/show.blade.php
@extends('skeleton.master')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>{{ $product->name }}</h3>
                <img src='{{asset("storage/$product->picture") }}'>
                <p> ${{ $product->price }}</p>
                <p>{{ $product->description }}</p>
                <span class="text-center">
                    <a href="{{ route('products.index') }}" class="btn btn-primary">Go Back</a>
                </span>
            </div>
        </div>
    </div>
@endsection

resources/views/skeleton/header.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>{{ config('app.name', 'Brighte')  }} @yield('title')</title>


<!-- Scripts -->
<script src="{{ asset('js/app.js') }}" defer></script>

<!-- Fonts -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

<!-- Styles -->
<link href="{{ asset('css/app.css') }}" rel="stylesheet">

resources/views/skeleton/master.blade.php
<html>
    <head>
        <title>Product Management System</title>
        @include("skeleton.header")
    </head>
    <body>
        @yield('content')
    </body>
</html>